name: Build YARA-X C API and Go Binary

on:
  workflow_dispatch:  # Enable manual triggering
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Install cargo-c
        run: cargo install cargo-c

      - name: Clone YARA-X repository
        run: git clone git@github.com:VirusTotal/yara-x.git

      - name: Checkout YARA-X version
        run: |
          cd yara-x
          git checkout tags/v.0.9.0

      - name: Build YARA-X C API
        run: |
          cd yara-x
          cargo cinstall -p yara-x-capi --release

      - name: Clone FileTrove repository
        run: git clone https://github.com/steffenfritz/FileTrove.git

      - name: Build Go Binary
        run: |
          cd FileTrove/cmd/ftrove
          task build

      - name: Create artifacts directory
        run: mkdir -p ../artifacts

      - name: Copy artifacts
        run: |
          cp /usr/local/lib/libyara_x.so ../artifacts/    # Ersetze durch den tatsächlichen Bibliotheksnamen
          cp ./ftrove ../artifacts/                        # Ersetze 'ftrove' durch den tatsächlichen Binary-Namen

      - name: Create archive of artifacts
        run: |
          cd ../artifacts
          tar -czvf artifacts.tar.gz *

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: FileTrove/cmd/artifacts/artifacts.tar.gz

