name: Build YARA-X C API and Go Binary

on:
  workflow_dispatch:  # Enable manual triggering
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install taskdev
        run: sudo snap install task --classic

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Install cargo-c
        run: cargo install cargo-c


        # Set up Go (for building the Go program)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'  # Use the desired Go version

      - name: Clone YARA-X repository
        run: git clone https://github.com/VirusTotal/yara-x.git

      - name: Checkout YARA-X version
        run: |
          cd yara-x
          git checkout tags/v0.9.0
          cargo cinstall -p yara-x-capi --release --destdir=$HOME/yara_install

      # Set environment variables so Go can find the library and headers
      - name: Set environment variables for Go
        run: |
          export PKG_CONFIG_PATH=$HOME/yara_install/lib/pkgconfig
          export CGO_CFLAGS="-I$HOME/yara_install/include"
          export CGO_LDFLAGS="-L$HOME/yara_install/lib"

      - name: Clone FileTrove repository
        run: git clone https://github.com/steffenfritz/FileTrove.git

      - name: Build Go Binary
        run: |
          cd FileTrove/cmd/ftrove
          task build

      - name: Create artifacts directory
        run: mkdir -p ../artifacts

      - name: Copy artifacts
        run: |

          cp $HOME/yara_install/lib/libyara_x_capi* ../artifacts/
          cp ./ftrove ../artifacts/


      - name: Create archive of artifacts
        run: |
          cd ../artifacts
          tar -czvf artifacts.tar.gz *

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: FileTrove/cmd/artifacts/artifacts.tar.gz

