name: Build and Cross-Compile Go & Rust Project

on:
  workflow_dispatch:  # Enable manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        arch: [x64, arm64]
        include:
          # macOS x64
          - platform: macos-latest
            arch: x64
          # Linux x64
          - platform: ubuntu-latest
            arch: x64
          # Linux ARM64
          - platform: ubuntu-latest
            arch: arm64
          # Windows x64
          - platform: windows-latest
            arch: x64

    runs-on: ${{ matrix.platform }}

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Rust and install cargo-c
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

          #- name: Cache Rust build
          #uses: actions/cache@v3
          #with:
          #path: |
          #~/.cargo/registry
          #~/.cargo/git
          #key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          #restore-keys: |
          #${{ runner.os }}-cargo-

      - name: Install cargo-c for Rust
        run: cargo install cargo-c

      # Install dependencies based on platform
      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install go
          brew install mingw-w64  # Required for Windows cross-compiling if needed in future

      - name: Install dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc musl-tools libssl-dev pkg-config gcc-aarch64-linux-gnu

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install golang --version=1.20.3
          choco install mingw

      # Clone the yara-x repository
      - name: Clone yara-x repository and build
        run: | 
          git clone https://github.com/VirusTotal/yara-x.git
          #git clone -b <branch-name> git@github.com:VirusTotal/yara-x.git
          mkdir -p $GITHUB_WORKSPACE/local/lib
          mkdir -p $GITHUB_WORKSPACE/local/include
          mkdir -p $GITHUB_WORKSPACE/local/lib/pkgconfig
          cd yara-x

          if [ "${{ matrix.platform }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "x64" ]; then
            rustup target add x86_64-unknown-linux-gnu
            export CC_x86_64_unknown_linux_gnu=gcc
            cargo cinstall -p yara-x-capi --release --target x86_64-unknown-linux-gnu --prefix=$GITHUB_WORKSPACE/local
          elif [ "${{ matrix.platform }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            rustup target add aarch64-unknown-linux-gnu
            export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
            cargo cinstall -p yara-x-capi --release --target aarch64-unknown-linux-gnu --prefix=$GITHUB_WORKSPACE/local
          elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
            rustup target add x86_64-apple-darwin
            export CC_x86_64_apple_darwin=clang
            export CXX_x86_64_apple_darwin=clang++
            cargo cinstall -p yara-x-capi --release --target x86_64-apple-darwin --prefix=$GITHUB_WORKSPACE/local
          elif [ "${{ matrix.platform }}" == "windows-latest" ]; then
            rustup target add x86_64-pc-windows-gnu
            export CC_x86_64_pc_windows_gnu=x86_64-w64-mingw32-gcc
            cargo cinstall -p yara-x-capi --release --target x86_64-pc-windows-gnu --prefix=$GITHUB_WORKSPACE/local
          fi

      # Build Go project (Cross-compiling for each platform)
      - name: Build Go project
        run: |
          export LIBRARY_PATH=$GITHUB_WORKSPACE/local/lib
          export C_INCLUDE_PATH=$GITHUB_WORKSPACE/local/include
          export PKG_CONFIG_PATH=$GITHUB_WORKSPACE/local/lib/pkgconfig
          
          if [ "${{ matrix.platform }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "x64" ]; then
            CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o build/linux64/ftrove
          elif [ "${{ matrix.platform }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o build/linux_arm64/ftrove
          elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
            CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o build/mac64/ftrove
          elif [ "${{ matrix.platform }}" == "windows-latest" ]; then
            CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o build/windows64/ftrove.exe
          fi

      # Upload the build artifacts (binaries and libraries)
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            build/

