name: crossbuild

on:
  push:
    tags:        
      - '*'
  #pull_request:
permissions:
  contents: read

jobs:
  xgo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - 
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Build ftrove
        uses: crazy-max/ghaction-xgo@682253ce1d3dd7a78c5120c703c9f3811dbf8cb2 # v3.0.0
        with:
          xgo_version: latest
          go_version: 1.21
          dest: build
          prefix: ftrove
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: true
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          pkg: ./cmd/ftrove
      -
        name: Build admftrove
        uses: crazy-max/ghaction-xgo@682253ce1d3dd7a78c5120c703c9f3811dbf8cb2 # v3.0.0
        with:
          xgo_version: latest
          go_version: 1.21
          dest: build
          prefix: admftrove
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: true
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          pkg: ./cmd/admftrove
      - 
        name: Create Release
        uses: actions/create-release@8d93430eddafb926c668181c71f579556f68668c # v1.0.0
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - 
        name: Upload Release Assets
        uses: glentiki/xbin-release-action@736088fa1388541bd9224f2749445ee3bd8890a5 # v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          assets_path: ./build
